name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout du code source

      - name: Construire l'image Docker
        run: |
          docker build -t ouldmahammed/hello-world-node:${{ github.sha }} .

      - name: Connexion à Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ouldmahammed --password-stdin

      - name: Pousser l'image Docker
        run: |
          docker tag ouldmahammed/hello-world-node:${{ github.sha }} ouldmahammed/hello-world-node:latest
          docker push ouldmahammed/hello-world-node:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Déployer sur Kubernetes
        run: |
          kubectl set image deployment/hello-world-node hello-world-node=ouldmahammed/hello-world-node:latest --record
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}